export const COUNTIES: string[] = [
    "Bedfordshire",
    "Berkshire",
    "Bristol",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cheshire",
    "City of London",
    "Cornwall",
    "Cumbria",
    "Derbyshire",
    "Devon",
    "Dorset",
    "Durham",
    "East Riding of Yorkshire",
    "East Sussex",
    "Essex",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Hampshire",
    "Herefordshire",
    "Hertfordshire",
    "Isle of Wight",
    "Kent",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Merseyside",
    "Norfolk",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Nottinghamshire",
    "Oxfordshire",
    "Rutland",
    "Shropshire",
    "Somerset",
    "South Yorkshire",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Tyne and Wear",
    "Warwickshire",
    "West Midlands",
    "West Sussex",
    "West Yorkshire",
    "Wiltshire",
    "Worcestershire",
    "Anglesey",
    "Brecknockshire",
    "Caernarfonshire",
    "Carmarthenshire",
    "Cardiganshire",
    "Denbighshire",
    "Flintshire",
    "Glamorgan",
    "Merioneth",
    "Monmouthshire",
    "Montgomeryshire",
    "Pembrokeshire",
    "Radnorshire",
    "Aberdeenshire",
    "Angus",
    "Argyllshire",
    "Ayrshire",
    "Banffshire",
    "Berwickshire",
    "Buteshire",
    "Cromartyshire",
    "Caithness",
    "Clackmannanshire",
    "Dumfriesshire",
    "Dunbartonshire",
    "East Lothian",
    "Fife",
    "Inverness-shire",
    "Kincardineshire",
    "Kinross",
    "Kirkcudbrightshire",
    "Lanarkshire",
    "Midlothian",
    "Morayshire",
    "Nairnshire",
    "Orkney",
    "Peeblesshire",
    "Perthshire",
    "Renfrewshire",
    "Ross-shire",
    "Roxburghshire",
    "Selkirkshire",
    "Shetland",
    "Stirlingshire",
    "Sutherland",
    "West Lothian",
    "Wigtownshire",
    "Antrim",
    "Armagh",
    "Down",
    "Fermanagh",
    "Londonderry",
    "Tyrone",
    "Yorkshire",
    "Cumberland",
    "Middlesex",
    "Huntingdonshire",
    "Westmorland"
];
