# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [infra/ci-cd]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mayur-rawte/github-angular-actions@latest
      - name: Install
        run: |
          npm install
      - name: Build
        run: ng build --prod
