# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: npm install
      - name: Test
        run: npm run test-headless
      - name: Build
        run: npm run build
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
      - name: Archive artifact
        uses: actions/upload-artifact@v1
        with:
          name: www
          path: www
